server:
  port: 8084

spring:
  application:
    name: medical-health-service

service:
  role: health
  websocket:
    enabled: false

infra:
  legacy-scheduler:
    enabled: false
  canal-cache-consumer:
    enabled: false
  domain-event-consumer:
    enabled: false
  delay:
    redis:
      enabled: false
